display_errors = Off
display_startup_errors = Off
log_errors = On
error_log = /proc/self/fd/2
expose_php = Off
allow_url_fopen = Off
allow_url_include = Off
file_uploads = Off
open_basedir = /var/www/html
disable_functions = exec,passthru,shell_exec,system,proc_open,popen,pcntl_exec
session.cookie_httponly = On
session.cookie_secure = On
